apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-2048-deployment
  labels:
    app: game-2048-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-2048-app
  template:
    metadata:
      labels:
        app: game-2048-app
    spec:
      containers:
        - name: game-2048-app
          image: piyush6042/game-2048:latest
          ports:
            - containerPort: 4000
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: game-2048-app-svc
spec:
  selector:
    app: game-2048-app
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: NodePort # Change this according to your environment (NodePort, LoadBalancer, etc.)
